"""Read/write the single source of truth: knowledge/case_record.json.

Schema (flat, as specified in the brief):
  facts[]          — every fact with full provenance + history[] + superseded
  contradictions[] — first-class; conflicts park here, never silently resolved
  changelog[]      — append-only, monotonic seq; every mutation is recorded
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from . import config


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def new_case_record(case_id: str) -> Dict:
    return {
        "case_id": case_id,
        "generated_at": now_iso(),
        "facts": [],
        "contradictions": [],
        "changelog": [],
    }


def load_case_record(path: Optional[Path] = None) -> Dict:
    path = path or config.CASE_RECORD_PATH
    if not Path(path).exists():
        return new_case_record("MACT-UNTITLED")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_case_record(record: Dict, path: Optional[Path] = None) -> None:
    path = path or config.CASE_RECORD_PATH
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    record["generated_at"] = now_iso()
    with open(path, "w", encoding="utf-8") as f:
        json.dump(record, f, indent=2, ensure_ascii=False)
        f.write("\n")


# --- id / seq helpers ----------------------------------------------------

def next_fact_id(record: Dict) -> str:
    return "F%03d" % (len(record["facts"]) + 1)


def next_contradiction_id(record: Dict) -> str:
    return "C%03d" % (len(record["contradictions"]) + 1)


def next_seq(record: Dict) -> int:
    return len(record["changelog"]) + 1


def add_changelog(record: Dict, action: str, summary: str,
                  fact_id: Optional[str] = None,
                  contradiction_id: Optional[str] = None,
                  field: Optional[str] = None) -> Dict:
    entry = {
        "seq": next_seq(record),
        "timestamp": now_iso(),
        "action": action,
        "field": field,
        "fact_id": fact_id,
        "contradiction_id": contradiction_id,
        "summary": summary,
    }
    record["changelog"].append(entry)
    return entry


# --- queries -------------------------------------------------------------

def active_facts(record: Dict) -> List[Dict]:
    return [f for f in record["facts"] if not f.get("superseded")]


def find_active_by_field(record: Dict, field: str) -> Optional[Dict]:
    for f in active_facts(record):
        if f["field"] == field:
            return f
    return None


def get_fact(record: Dict, fact_id: str) -> Optional[Dict]:
    for f in record["facts"]:
        if f["id"] == fact_id:
            return f
    return None


# --- changelog.md rendering ---------------------------------------------

def changelog_md_text(record: Dict) -> str:
    """Render the changelog as markdown text (no file I/O)."""
    lines = [
        "# Changelog — %s" % record.get("case_id", ""),
        "",
        "Append-only record of every knowledge-base mutation. Generated by the",
        "reconciler; do not hand-edit. Contradictions caught by the loop are",
        "marked **CONTRADICTION**.",
        "",
        "| seq | when | action | field | ref | summary |",
        "|----:|------|--------|-------|-----|---------|",
    ]
    for e in record["changelog"]:
        ref = e.get("fact_id") or e.get("contradiction_id") or ""
        action = e["action"]
        if action == "contradiction":
            action = "**CONTRADICTION**"
        summary = (e.get("summary") or "").replace("|", "\\|")
        lines.append("| %d | %s | %s | %s | %s | %s |" % (
            e["seq"], e["timestamp"], action, e.get("field") or "", ref, summary))
    lines.append("")
    return "\n".join(lines)


def render_changelog_md(record: Dict, path: Optional[Path] = None) -> str:
    """Write the changelog markdown to disk (default knowledge/changelog.md)."""
    path = path or config.CHANGELOG_MD_PATH
    text = changelog_md_text(record)
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return text
